module.exports = {
  '*': require('./all'),
  '/': require('./homepage'),
  headphones: {
    '/': require('./headphones/index'),
    'apple-wired': require('./headphones/apple-wired'),
    'bose-quietcomfort-25': require('./headphones/bose-quietcomfort-25'),
    'bose-quietcomfort-35-ii': require('./headphones/bose-quietcomfort-35-ii'),
    'goojodoq-wireless-sleeping': require('./headphones/goojodoq-wireless-sleeping'),
    'jabra-elite-65t': require('./headphones/jabra-elite-65t'),
    'jaybird-run': require('./headphones/jaybird-run'),
    'maxrock-wired-sleeping': require('./headphones/maxrock-wired-sleeping'),
    'maxrock-wireless-sleeping': require('./headphones/maxrock-wireless-sleeping'),
    'philips-oneill-sho9560-28': require('./headphones/philips-oneill-sho9560-28'),
    'pixel-buds-2': require('./headphones/pixel-buds-2'),
    'pixel-usb-c-earbuds': require('./headphones/pixel-usb-c-earbuds'),
    'sony-mdr-j10-h.ear': require('./headphones/sony-mdr-j10-h.ear'),
  },
  thoughts: {
    '2d-automaton': require('./thoughts/2d-automaton'),
    'cellular-automaton': require('./thoughts/cellular-automaton'),
    'lissajous-curve': require('./thoughts/lissajous-curve'),
    'last-fm': require('./thoughts/last-fm'),
    minesweeper: require('./thoughts/minesweeper/index'),
    paint: require('./thoughts/paint'),
    yahtzee: require('./thoughts/yahtzee'),
    'earth-rotating-sprite-animation': require('./thoughts/earth-rotating-sprite-animation'),
    'color-canvas': require('./thoughts/color-canvas'),
    'raining-paint': require('./thoughts/raining-paint'),
    'unique-stars': require('./thoughts/unique-stars'),
    'using-canvas-to-make-patterns-with-circles': require('./thoughts/using-canvas'),
    'in-view-text-animation': require('./thoughts/in-view-text-animation'),
  },
};
