module.exports = {
  '*': require('./all'),
  '/': require('./homepage'),
  thoughts: {
    '2d-automaton': require('./thoughts/2d-automaton'),
    'cellular-automaton': require('./thoughts/cellular-automaton'),
    'lissajous-curve': require('./thoughts/lissajous-curve'),
    'last-fm': require('./thoughts/last-fm'),
    minesweeper: require('./thoughts/minesweeper/index'),
    paint: require('./thoughts/paint'),
    'earth-rotating-sprite-animation': require('./thoughts/earth-rotating-sprite-animation'),
    'color-canvas': require('./thoughts/color-canvas'),
    'raining-paint': require('./thoughts/raining-paint'),
    'unique-stars': require('./thoughts/unique-stars'),
    'using-canvas-to-make-patterns-with-circles': require('./thoughts/using-canvas'),
    'headphones-apple-wired': require('./thoughts/headphones-apple-wired'),
    'headphones-bose-quietcomfort-25': require('./thoughts/headphones-bose-quietcomfort-25'),
    'headphones-bose-quietcomfort-35-ii': require('./thoughts/headphones-bose-quietcomfort-35-ii'),
    'headphones-goojodoq-wireless-sleeping': require('./thoughts/headphones-goojodoq-wireless-sleeping'),
    'headphones-jabra-elite-65t': require('./thoughts/headphones-jabra-elite-65t'),
    'headphones-jaybird-run': require('./thoughts/headphones-jaybird-run'),
    'headphones-maxrock-wired-sleeping': require('./thoughts/headphones-maxrock-wired-sleeping'),
    'headphones-maxrock-wireless-sleeping': require('./thoughts/headphones-maxrock-wireless-sleeping'),
    'headphones-philips-oneill-sho9560-28': require('./thoughts/headphones-philips-oneill-sho9560-28'),
    'headphones-pixel-buds-2': require('./thoughts/headphones-pixel-buds-2'),
    'headphones-pixel-usb-c-earbuds': require('./thoughts/headphones-pixel-usb-c-earbuds'),
    'headphones-sony-mdr-j10-h.ear': require('./thoughts/headphones-sony-mdr-j10-h.ear'),
    'headphones': require('./thoughts/headphones'),
  },
};
